Gradle Cache Support

diff --git a/Example Mod/gradlew b/Example Mod/gradlew
--- a/Example Mod/gradlew
+++ b/Example Mod/gradlew
@@ -71,15 +71,15 @@ app_path=$0
 
 # Need this for daisy-chained symlinks.
 while
-APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
-[ -h "$app_path" ]
+    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
+    [ -h "$app_path" ]
 do
-  ls=$( ls -ld "$app_path" )
-  link=${ls#*' -> '}
-  case $link in             #(
-  /*)   app_path=$link ;; #(
-  *)    app_path=$APP_HOME$link ;;
-  esac
+    ls=$( ls -ld "$app_path" )
+    link=${ls#*' -> '}
+    case $link in             #(
+      /*)   app_path=$link ;; #(
+      *)    app_path=$APP_HOME$link ;;
+    esac
 done
 
 # This is normally unused
@@ -92,14 +92,14 @@ APP_HOME=$( cd -P "${APP_HOME:-./}" > /dev/null && printf '%s\n' "$PWD" ) || exi
 MAX_FD=maximum
 
 warn () {
-  echo "$*"
+    echo "$*"
 } >&2
 
 die () {
-  echo
-  echo "$*"
-  echo
-  exit 1
+    echo
+    echo "$*"
+    echo
+    exit 1
 } >&2
 
 # OS specific support (must be 'true' or 'false').
@@ -108,56 +108,56 @@ msys=false
 darwin=false
 nonstop=false
 case "$( uname )" in                #(
-CYGWIN* )         cygwin=true  ;; #(
-Darwin* )         darwin=true  ;; #(
-MSYS* | MINGW* )  msys=true    ;; #(
-NONSTOP* )        nonstop=true ;;
+  CYGWIN* )         cygwin=true  ;; #(
+  Darwin* )         darwin=true  ;; #(
+  MSYS* | MINGW* )  msys=true    ;; #(
+  NONSTOP* )        nonstop=true ;;
 esac
 
 
 
 # Determine the Java command to use to start the JVM.
 if [ -n "$JAVA_HOME" ] ; then
-  if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
-    # IBM's JDK on AIX uses strange locations for the executables
-    JAVACMD=$JAVA_HOME/jre/sh/java
-  else
-    JAVACMD=$JAVA_HOME/bin/java
-  fi
-  if [ ! -x "$JAVACMD" ] ; then
-    die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+        # IBM's JDK on AIX uses strange locations for the executables
+        JAVACMD=$JAVA_HOME/jre/sh/java
+    else
+        JAVACMD=$JAVA_HOME/bin/java
+    fi
+    if [ ! -x "$JAVACMD" ] ; then
+        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
 
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
-  fi
+    fi
 else
-  JAVACMD=java
-  if ! command -v java >/dev/null 2>&1
-  then
-    die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+    JAVACMD=java
+    if ! command -v java >/dev/null 2>&1
+    then
+        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
-  fi
+    fi
 fi
 
 # Increase the maximum file descriptors if we can.
 if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
-  case $MAX_FD in #(
-  max*)
-  # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
-  # shellcheck disable=SC2039,SC3045
-    MAX_FD=$( ulimit -H -n ) ||
-      warn "Could not query maximum file descriptor limit"
-  esac
-  case $MAX_FD in  #(
-  '' | soft) :;; #(
-  *)
-  # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
-  # shellcheck disable=SC2039,SC3045
-    ulimit -n "$MAX_FD" ||
-      warn "Could not set maximum file descriptor limit to $MAX_FD"
-  esac
+    case $MAX_FD in #(
+      max*)
+        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
+        # shellcheck disable=SC2039,SC3045
+        MAX_FD=$( ulimit -H -n ) ||
+            warn "Could not query maximum file descriptor limit"
+    esac
+    case $MAX_FD in  #(
+      '' | soft) :;; #(
+      *)
+        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
+        # shellcheck disable=SC2039,SC3045
+        ulimit -n "$MAX_FD" ||
+            warn "Could not set maximum file descriptor limit to $MAX_FD"
+    esac
 fi
 
 # Collect all arguments for the java command, stacking in reverse order:
@@ -170,32 +170,32 @@ fi
 
 # For Cygwin or MSYS, switch paths to Windows format before running java
 if "$cygwin" || "$msys" ; then
-  APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
+    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
 
-  JAVACMD=$( cygpath --unix "$JAVACMD" )
+    JAVACMD=$( cygpath --unix "$JAVACMD" )
 
-  # Now convert the arguments - kludge to limit ourselves to /bin/sh
-  for arg do
-    if
-    case $arg in                                #(
-    -*)   false ;;                            # don't mess with options #(
-    /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
-      [ -e "$t" ] ;;                      #(
-    *)    false ;;
-    esac
-    then
-      arg=$( cygpath --path --ignore --mixed "$arg" )
-    fi
-    # Roll the args list around exactly as many times as the number of
-    # args, so each arg winds up back in the position where it started, but
-    # possibly modified.
-    #
-    # NB: a `for` loop captures its iteration list before it begins, so
-    # changing the positional parameters here affects neither the number of
-    # iterations, nor the values presented in `arg`.
-    shift                   # remove old arg
-    set -- "$@" "$arg"      # push replacement arg
-  done
+    # Now convert the arguments - kludge to limit ourselves to /bin/sh
+    for arg do
+        if
+            case $arg in                                #(
+              -*)   false ;;                            # don't mess with options #(
+              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
+                    [ -e "$t" ] ;;                      #(
+              *)    false ;;
+            esac
+        then
+            arg=$( cygpath --path --ignore --mixed "$arg" )
+        fi
+        # Roll the args list around exactly as many times as the number of
+        # args, so each arg winds up back in the position where it started, but
+        # possibly modified.
+        #
+        # NB: a `for` loop captures its iteration list before it begins, so
+        # changing the positional parameters here affects neither the number of
+        # iterations, nor the values presented in `arg`.
+        shift                   # remove old arg
+        set -- "$@" "$arg"      # push replacement arg
+    done
 fi
 
 
@@ -209,14 +209,14 @@ DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
 #     treated as '${Hostname}' itself on the command line.
 
 set -- \
-  "-Dorg.gradle.appname=$APP_BASE_NAME" \
-  -jar "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
-  "$@"
+        "-Dorg.gradle.appname=$APP_BASE_NAME" \
+        -jar "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
+        "$@"
 
 # Stop when "xargs" is not available.
 if ! command -v xargs >/dev/null 2>&1
 then
-  die "xargs is not available"
+    die "xargs is not available"
 fi
 
 # Use "xargs" to parse quoted args.
@@ -239,10 +239,10 @@ fi
 #
 
 eval "set -- $(
-  printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
-    xargs -n1 |
-    sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
-    tr '\n' ' '
-)" '"$@"'
+        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
+        xargs -n1 |
+        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
+        tr '\n' ' '
+    )" '"$@"'
 
 exec "$JAVACMD" "$@"
